### ISSUE TITLE
The brain tilt after running recon-all -i

### ISSUE THREAD

**Issue by Harvardzjx** [vistalab/vistasoft#107]
The brain tilt after running recon-all -i in freesurfer. How can we correct it ?

![image](https://cloud.githubusercontent.com/assets/8097446/3504536/12e6f22a-0649-11e4-866f-adb4ed44ae66.png)

**Comment by JWinawer** [comment]
I believe these questions were answered by email. I am closing the issue. Please re-open if the issues remain.
