### ISSUE TITLE
problem while running mrInit

### ISSUE THREAD

**Issue by ahmadi123** [vistalab/vistasoft#124]
Hello,
I am trying to run mrInit on my data. but it fails to work properly. every time, I get a warning:
"Warning: No freqdim field set in the nifti. Assuming freqdim = 1.Nifti stored at:/mnt/host/migraine_aura_fmri/subjectA3/retmap/expanding_ring1.nii.gz 
In niftiApplyXform at 88
  In niftiApplyAndCreateXform at 28
  In mrInit at 187 
Warning: No phasedim field set in the nifti. Assuming phasedim = 2.
Nifti stored at:/mnt/host/migraine_aura_fmri/subjectA3/retmap/expanding_ring1.nii.gz 
> In niftiApplyXform at 95
  In niftiApplyAndCreateXform at 28
  In mrInit at 187"
The final error however is not the same alway. Sometimes I get this error:" Index exceeds matrix dimensions.
Error in loadtSeries (line 61)
    nii = niftiSet(nii,'Data', data(:,:,:,keepFrame));
Error in computeMeanMap (line 62)
            [~, nii] = loadtSeries(vw,scan);
Error in loadMeanMap (line 40)
        vw = computeMeanMap(vw,0);
Error in betweenScanMotComp (line 33)
vw = loadMeanMap(vw);
Error in motionCompNestaresFull (line 33)
vw = betweenScanMotComp(vw, bwScansDataType, baseScan, tgtScans);
Error in mrInit (line 272)
            motionCompNestaresFull(INPLANE{1}, [], ..."
and sometimes I get this error: "Reference to non-existent field 'scanParams'. Error in viewGetSession (line 135)
val = length(dataTYPES(dataType).scanParams); %TODO: Use dtGet
Error in viewGet (line 315)
val = viewGetSession(vw,param,varargin{:});
Error in motionCompNestaresFull (line 20)
if notDefined('tgtScans'),      tgtScans = 1:viewGet(vw,'numScans'); 
end
Error in mrInit (line 272)
motionCompNestaresFull(INPLANE{1}, [], ..."
I also tried mrvTest to help me ged rid of the errors. but, it failed in 2 functions: 
 test_glm .............................................. FAILED in    17.819979 seconds
 test_xformInplaneToVolume ............................. FAILED in    55.373092 seconds
I deleted the vista data folder, downloaded it again and tried mrvTest for another time. the above functions failed again.I am using a linux system and as far as I know all the functions should pass in mac and linux!
Could you please help me?
Best regards,
Ahmadi

**Comment by JWinawer** [comment]
ahmadi123:

If you post the data (inplane + functionals) and your initialize script, then I will run it on my machine and  try to debug. 

Jon

**Comment by ahmadi123** [comment]
Hi,
many thanks for your reply. I already have solved the problem. The problem was related to cliping frames.Now, It is working.
Thank you and best regards,
Khazar Ahmadi
