### ISSUE TITLE
mrInit does not use nifti header information to transform scans to canonical ordering

### ISSUE THREAD

**Issue by liorbu** [vistalab/vistasoft#125]
Recently multiple users have independently encountered an alignment issue with some scans coming off of NIMS. It seems this is a result of the NIMS pipeline preserving the data as it comes off the scanner, and possibly violating some of mrInit expectations as to slice ordering. The result is that the inplanes and functional data are misaligned, so that after properly aligning inplanes to the anatomicals, the functionals would be flipped to both (the result being, of course, nonsensical). The current solution to this is to apply the niftiApplyCannonicalXform function to the inplanes manually prior to initializing the scan. This seems to have solved the issue in all cases encountered thus far. The apparent obvious fix is to apply the niftiApplyCannonicalXform to inplanes as part of mrInit, but this should be considered for any potential repercussions down the processing pipeline (as well as whether or not this should be automatically applied to functionals, as that is more time-consuming and resulted in mixed results when attempted, sometimes causing extensive errors in other mrVista functions. Most notably, not being able to open the alignment UI).

**Comment by JWinawer** [comment]
Thanks for alerting us of the issue. If someone could post an example data set somewhere, I will take a look.

-Jon

**Comment by JWinawer** [comment]
So the relevant files in your example sessions would be:
- 24mm_Inplane_MUX (Inplane)
- BOLD_mux3_24mm_1sec (functional)

Correct?

**Comment by liorbu** [comment]
Well, the current manual fix is to apply the canonical transformation only
to the inplanes. In the example sets given, one has a "good" inplane file
and the other a problematic one. The functionals seem to come out OK from
the scanner (in terms of mrVista "expectations") or some kind of
transformation is already integrated into the pipeline. Either way, there
was no need to do anything with functionals to get things working.

Best,
Lior

On Tue, Jan 13, 2015 at 12:55 PM, Jonathan Winawer <notifications@github.com

**Comment by ktravis1** [comment]
Hello -  Noticed this thread and just checked our most recent diffusion scans.  For scans collected at CNI before Nov. 24th it was not necessary to rotate bvecs to CanXForm, but found that for our scans collected at CNI after Dec 5th that bves were misaligned. Turning on the CanXForm flag in the dtiInit appears to fix the problem. Wondering if there was a system update/change that may affect others? 

Thanks, 
Katie

**Comment by rfdougherty** [comment]
Hi Katie,

Yes, there was a change. Thanks for reminding me! I forgot to notify the 
vistasoft team.

Prior to the NIMS update in November, the gradient directions in the 
bvecs file produced by NIMS were not rotated according to the Rx 
rotation matrix. It turns out that leaving the CanXform flag off in 
mrVista would (very coincidentally) fix this issue for axial scans 
(which just about every one does).

But this was all just wrong and would give incorrect bvecs for anything 
other than an axial scan (and for data processed outside of mrVista). 
So, we fixed nims to apply the Rx rotation matrix to the gradient 
directions when saving bvecs. Now you should turn on the CanXform flag 
(which, in general, should be used) and the bvecs file that we produce 
should work with needing to be adjusted in software packages outside of 
mrVista. And it should work for non-axial prescriptions.

Sorry for not letting you know. But I'm happy to hear that you checked 
your data and sorted it out!

cheers,
bob

**Comment by JWinawer** [comment]
You need a functional scan to initialize a vista session. And we want to be
sure that the functional and Inplane come out co-registered after
initialization. So to test a data set, I need an Inplane and a functional.
I am going to assume that the files called 'BOLD_mux3_24mm_1sec' are
intended to be co-registered to '24mm_Inplane_MUX'.


On Tue, Jan 13, 2015 at 4:10 PM, liorbu <notifications@github.com> wrote:

> Well, the current manual fix is to apply the canonical transformation only
> to the inplanes. In the example sets given, one has a "good" inplane file
> and the other a problematic one. The functionals seem to come out OK from
> the scanner (in terms of mrVista "expectations") or some kind of
> transformation is already integrated into the pipeline. Either way, there
> was no need to do anything with functionals to get things working.
>
> Best,
> Lior
>
> On Tue, Jan 13, 2015 at 12:55 PM, Jonathan Winawer <
> notifications@github.com
> > wrote:
>
> > So the relevant files in your example sessions would be:
> >
> > - 24mm_Inplane_MUX (Inplane)
> > - BOLD_mux3_24mm_1sec (functional)
> >
> > Correct?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/vistalab/vistasoft/issues/125#issuecomment-69818025>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vistalab/vistasoft/issues/125#issuecomment-69820613>.
>



-- 
Jonathan Winawer
Assistant Professor of Psychology and Neural Science

New York University
6 Washington Place
New York, NY, 10003
(212) 998-7922 (phone)
(212) 995-4018 (fax)
jonathan.winawer@nyu.edu
http://psych.nyu.edu/winawer/

**Comment by liorbu** [comment]
Yes, that's correct. I just wanted to be clear on the issue. Thanks for
looking into this.

**Comment by ktravis1** [comment]
Thanks Bob for the info - makes sense.  Sorry if I interrupted or confused the thread.  - KT

**Comment by JWinawer** [comment]
See pull request: https://github.com/vistalab/vistasoft/pull/126
