### ISSUE TITLE
niftiWrite does not write file names with extension '.nii'

### ISSUE THREAD

**Issue by mleming** [vistalab/vistasoft#129]
Using MATLAB_R2013a on Mac OSX Yosemite.

When I attempt to write a NIFTI-1 file, the following happens:

    >>nif = niftiReadMatlab('nifti_file.nii.gz');
    >>cd ..
    >>niftiWrite(nif, 'output.nii')
   
    Error using getArchiveEntries (line 92)
    File "output" does not exist.

    Error in gzip (line 47)
    entries = getArchiveEntries(files, rootDir, mfilename);

    Error in niftiWrite (line 50)
    gzip(fullfile(p,n));

Even so, the same command would work and output 'output.nii.gz', if I were to write

    >>niftiWrite(nif, 'output.nii.gz')

or

    >>niftiWrite(nif, 'output')

**Comment by lmperry** [comment]
Pull request is pending. Once it's merged this issue should be fixed.

**Comment by lmperry** [comment]
This issue should now be resolved with PR #130  - please let us know if the issue remains.
