### ISSUE TITLE
Error using fmincon when estimating HRF

### ISSUE THREAD

**Issue by allanhummer** [vistalab/vistasoft#131]
Using the latest github mrVista version and Matlab 8.3. I'm experiencing an error after the first fFit. I think it is similar to the one described in issue #91.
Allan

[hrfModelSearchFit]:Estimating HRF
    Two gamma function: [peak1 width1 peak2 width2 -weight2]
    Input (Default):    [5.4000 5.2000 10.8000 7.3500 0.3500]
    Search range (min): [2.7000 2.6000 5.4000 3.6750 0.0000]
    Search range (max): [10.8000 10.4000 21.6000 14.7000 0.7000]
    Grid stage output:  [5.1300 3.3800 7.0200 11.3925 0.0700](33 min)
Error using fmincon (line 712)
FMINCON requires all values returned by user functions to be of data type double.

Error in hrfModelSearchFit (line 97)
hrfParams = ...

Error in rmHrfSearchFit (line 247)
outParams = hrfModelSearchFit(data,prediction,hrfParams,params);

Error in rmMain (line 141)
        [view,params] = rmHrfSearchFit(view,params);

Error in RETPostSegmentationAnalysis (line 209)
        GrayView=rmMain(GrayView{m}{i},[],5);

Using Matlab 8.1. I get a similar, but slightly different Error. Its about fmincons default algorithm, which was different in that version, not being suitable for the data.

**Comment by rosemary-le** [comment]
I received the same error message (Matlab 2012b) when trying to estimate the HRF -- "FMINCON requires all values returned by user functions to be of data type double."

Best,
Rosemary
--------------------

Error using fmincon (line 779)
FMINCON requires all values returned by user functions to be of data type double.

Error in hrfModelSearchFit (line 97)
hrfParams = ...

Error in rmHrfSearchFit (line 247)
outParams = hrfModelSearchFit(data,prediction,hrfParams,params);

Error in rmMain (line 147)
 [view, params] = rmHrfSearchFit(view, params);

**Comment by JWinawer** [comment]
Can you make sure you have the latest git version of vistasoft and vistatest, and then run 

> test_prf_full

and see if it produces the same error in the hrf fit? It might also be good to run the whole mrvTest. For example:

> logfile = mrvTest([], 'bold', true)
> edit(logfile)

Jon

**Comment by rosemary-le** [comment]
test_prf_full does look like it produces the same error: 

- - - 
Error using fmincon (line 779)
FMINCON requires all values returned by user functions to be of data type double.

Error in hrfModelSearchFit (line 97)
hrfParams = ...

Error in rmHrfSearchFit (line 247)
outParams = hrfModelSearchFit(data,prediction,hrfParams,params);

Error in rmMain (line 141)
[view,params] = rmHrfSearchFit(view,params);

Error in test_prf_full (line 61)
vw = rmMain(vw,'RV1.mat' ,5,'min pRF size', 0.5, 'max pRF size', 3,...

**Comment by JWinawer** [comment]
What version of MATLAB are you using? I tested this code using MATLAB2014a
and 2014b and it ran without error.

On Wed, Jul 22, 2015 at 5:48 PM, Rosemary Le <notifications@github.com>
wrote:

> test_prf_full does look like it produces the same error:
> ------------------------------
>
> Error using fmincon (line 779)
> FMINCON requires all values returned by user functions to be of data type
> double.
>
> Error in hrfModelSearchFit (line 97)
> hrfParams = ...
>
> Error in rmHrfSearchFit (line 247)
> outParams = hrfModelSearchFit(data,prediction,hrfParams,params);
>
> Error in rmMain (line 141)
> [view,params] = rmHrfSearchFit(view,params);
>
> Error in test_prf_full (line 61)
> vw = rmMain(vw,'RV1.mat' ,5,'min pRF size', 0.5, 'max pRF size', 3,...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vistalab/vistasoft/issues/131#issuecomment-123876696>.
>



-- 
Jonathan Winawer
Assistant Professor of Psychology and Neural Science

New York University
6 Washington Place
New York, NY, 10003
(212) 998-7922 (phone)
(212) 995-4018 (fax)
jonathan.winawer@nyu.edu
http://psych.nyu.edu/winawer/

**Comment by rosemary-le** [comment]
That might be my problem, I am running MATLAB2012b.

**Comment by JWinawer** [comment]
Well, that is probably the difference. But we'd like this to run on
multiple versions of MATLAB. Will look into this...

On Wed, Jul 22, 2015 at 6:02 PM, Rosemary Le <notifications@github.com>
wrote:

> That might be my problem, I am running MATLAB2012b.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vistalab/vistasoft/issues/131#issuecomment-123880014>.
>



-- 
Jonathan Winawer
Assistant Professor of Psychology and Neural Science

New York University
6 Washington Place
New York, NY, 10003
(212) 998-7922 (phone)
(212) 995-4018 (fax)
jonathan.winawer@nyu.edu
http://psych.nyu.edu/winawer/

**Comment by JWinawer** [comment]
Given that the tests pass for Matlab versions 2014a-2017a, I think it's time to close the issue and accept that we don't support Matlab2012b. Too many differences.
