### ISSUE TITLE
using rxAlign, are there the other two views?  sagittal or axial views

### ISSUE THREAD

**Issue by bjy2952** [vistalab/vistasoft#141]
Hi everybody,
I am learning to use mrVista to analyse my fMRI data. There is one question, could you help me?

I have done alignment using rxAlign. I want to know if there are another two views, sagittal and axial views, of prescribed slice and reference slice. I need to check the alignment in the other two views.

Or are there other ways to check alignment from different views?

Thanks.

**Comment by JWinawer** [comment]
In the RxAlign GUI, there is a dropdown menu item under 'Window' called
'Open interpolated 3-view window'.

In my scans, there are typically few slices compared to pixels in the plane
(say, 24, compared to ~200), so the other two views tend be less
informative. [image: Inline image 1]

Jon


On Sun, Aug 16, 2015 at 10:16 PM, bjy2952 <notifications@github.com> wrote:

> Hi everybody,
> I am learning to use mrVista to analyse my fMRI data. There is one
> question, could you help me?
>
> I have done alignment using rxAlign. I want to know if there are another
> two views, sagittal and axial views, of prescribed slice and reference
> slice. I need to check the alignment in the other two views.
>
> Or are there other ways to check alignment from different views?
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vistalab/vistasoft/issues/141>.
>



-- 
Jonathan Winawer
Assistant Professor of Psychology and Neural Science

New York University
6 Washington Place
New York, NY, 10003
(212) 998-7922 (phone)
(212) 995-4018 (fax)
jonathan.winawer@nyu.edu
http://psych.nyu.edu/winawer/

**Comment by bjy2952** [comment]
JWinawer, thank you very much.
