### ISSUE TITLE
can not browse the VISTA wiki, need sunetid

### ISSUE THREAD

**Issue by bjy2952** [vistalab/vistasoft#143]
hello everybody, can you come into the vista wiki page? I can yesterday, but this morning I found I can not. It need me to login with the SUnetid, but I do not have one. Do you have any other method to browse? Thank you.

**Comment by wandell** [comment]
The site was hacked.  Trying to restore.

**Comment by bjy2952** [comment]
oh, this is a bad news. hope it can work as soon as possible. thanks for telling.

**Comment by lmperry** [comment]
The wiki has been restored.

**Comment by bjy2952** [comment]
great, thank you.
