### ISSUE TITLE
Creating Bvecs ang Bvals error using dtiRawBuildBvecs

### ISSUE THREAD

**Issue by shrimpj** [vistalab/vistasoft#147]
Hi All,
I try to use dtiRawBuildBvecs.m to create bvecs and bvals for FSL using code shared on following link:
https://github.com/vistalab/vistasoft/blob/master/mrDiffusion/preprocess/dtiRawBuildBvecs.m

I have DTI imaging with b value = 1000 and a dwepi.27.grads file of 26 directions from GE scanner. I used dtiRawBuildBvecs(26, xform = [], dwepi.27.grads, 1000, 'dti.nii.gz') to call function, but error
message says unexpected expression. I would like to know why is that? Any suggestions would be appreciated!

Best Wishes,
Joyce

**Comment by francopestilli** [comment]
Hi Joyce, can you please provide more information about the error?

**Comment by shrimpj** [comment]
Hi feancopestilli, 

Thank you so much for your reply. The error message was only one line saying matlab unexpected expression. That's why I was thinking do I need to load nifty file before using dtiRawBuildBvecs function? For instance, do I need load dwepi.27.grads files somehow? 'dti.nii.gz' is the nifiti imaging data file. Is that alright to call in the function directly?

dtiRawBuildBvecs(26, xform = [], dwepi.27.grads, 1000, 'dti.nii.gz')
Cheers!

**Comment by wandell** [comment]
The call is not correct.  The argument, xform = [], is wrong.

Brian


Stanford

**Comment by francopestilli** [comment]
Also try avoiding naming your files using 'dots,' e.g., change dwepi.27.grads -> dwepi_27.grads

**Comment by shrimpj** [comment]
Dear Brian,

The argument, xform = [], is suggested by introduction of this function as
I don't want to rotate images to fit scanner coordinate. Would you please
give me more information regarding the arguments? Thank you so much in
advance!

BW,
Joyce

2015-12-06 9:53 GMT-08:00 Brian Wandell <notifications@github.com>:

> The call is not correct. The argument, xform = [], is wrong.
>
> Brian
>
>
> Stanford
> Sent from mobile device
>

**Comment by lmperry** [comment]
Hello Joyce, 

What Brian was pointing out was that the structure of your input argument is not correct. The issue is with ``` xform = []```. By writing ```dtiRawBuildBvecs(26, xform = [], dwepi.27.grads, 1000, 'dti.nii.gz') ``` you're making a variable assignment where you should simply provide  ```dtiRawBuildBvecs(26, [], dwepi.27.grads, 1000, 'dti.nii.gz') ```. 

Please a look at the [example suage](https://github.com/vistalab/vistasoft/blob/master/mrDiffusion/preprocess/dtiRawBuildBvecs.m#L40-L44)

**Comment by shrimpj** [comment]
Hi Imperry, Thank you so much for your reply! It's more clear now!
