### ISSUE TITLE
css branch ready for primetime?

### ISSUE THREAD

**Issue by rosemary-le** [vistalab/vistasoft#157]
Or are there things to be worked out that we should be aware of? (It seems to be running great from my end and like a great thing the master branch should have!)

**Comment by JWinawer** [comment]
I think merging css branch with master is a good idea. I have made a large
number of other minor edits in this css branch (in addition to adding a new
pRF model type), all intended toward either better functionality or better
readability of code. I have been using the css branch for several months
without problems. I also just ran (again) the mrvTest code and all
validation scripts passed.

Could you (Rosemary) also run mrvTest on the css branch? I would like
confirmation that the validation tests pass on at least one other system
before merging branches. The command for the longer version of the
validation test (which took 6 min to run on my machine) would be:

mrvTest('~/myLogFile.m', 'bold', true)
Reminder: you need the vistadata svn repository on your path to run
mrvTest, and the mrvTest github repository.

-Jon

On Wed, Jan 20, 2016 at 6:22 PM, Rosemary Le <notifications@github.com>
wrote:

> Or are there things to be worked out that we should be aware of? (It seems
> to be running great from my end and like a great thing the master branch
> should have!)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vistalab/vistasoft/issues/157>.
>



-- 
Jonathan Winawer
Assistant Professor of Psychology and Neural Science

New York University
6 Washington Place
New York, NY, 10003
(212) 998-7922 (phone)
(212) 995-4018 (fax)
jonathan.winawer@nyu.edu
http://psych.nyu.edu/winawer/

**Comment by rosemary-le** [comment]
Thanks, Jon. 
It didn't pass all the tests and I've attached the log file here. 
Also a clarification, there is a mrvTest.m file in the vistadata svn repository, but no mrvTest git repository (or at least not that I could find). Just wanted to check that this is consistent with what you have too.

Thanks again,
Rosemary

[myLogFile.txt](https://github.com/vistalab/vistasoft/files/99863/myLogFile.txt)

**Comment by JWinawer** [comment]
Re paths: I incorrectly referred to the 'mrvTest' github repository, when I
should have referred to the 'vistatest' github repository. (Side note: I
think we should merge vistatest into vistasoft - not the data in vistadata,
but the code in vistatest. This will reduce the number of repositories to
two - one for code and one for data. But we can do that after merging css
into the master branch). Meantime, on your path you should have vistadata
 (svn), vistatest (github) and vistasoft (github). The function mrvTest.m
should be in vistatest, not vistadata. I assume all this is correct or else
your validation code would not have run at all.

Re your validation log: The good thing is that almost all validation
functions passed. The bad thing is that not all validations passed. You
have two failures, which look to have the same source, but one I do not
understand. (I don't have this failure on my machine).

Could you call these two functions from Matlab and see what happens?
> test_CleanUpSVN % to reset vistadata svn repository in case anything was
overwritten or is out of date
> test_prf % to test whether the prf validation code works when not called
inside the big mrvTest script

-Jon

On Thu, Jan 21, 2016 at 3:47 PM, Rosemary Le <notifications@github.com>
wrote:

> Thanks, Jon.
> It didn't pass all the tests and I've attached the log file here.
> Also a clarification, there is a mrvTest.m file in the vistadata svn
> repository, but no mrvTest git repository (or at least not that I could
> find). Just wanted to check that this is consistent with what you have too.
>
> Thanks again,
> Rosemary
>
> myLogFile.txt
> <https://github.com/vistalab/vistasoft/files/99863/myLogFile.txt>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vistalab/vistasoft/issues/157#issuecomment-173703110>.
>



-- 
Jonathan Winawer
Assistant Professor of Psychology and Neural Science

New York University
6 Washington Place
New York, NY, 10003
(212) 998-7922 (phone)
(212) 995-4018 (fax)
jonathan.winawer@nyu.edu
http://psych.nyu.edu/winawer/

**Comment by rosemary-le** [comment]
The good thing is that test_CleanUpSVN seems to run without a problem:
```
>> test_CleanUpSVN

ans =

     0
```
but test_prf does return an error, which I will include in a text file here.
[test_prf.txt](https://github.com/vistalab/vistasoft/files/100056/test_prf.txt)

(And indeed the mrvTest function is in the vistatest github repository, thanks for the clarification.)
 
Rosemary

**Comment by JWinawer** [comment]
It looks like vistasoft is not finding the INPLANE anatomy nifti file. You
might have an outdated vistadata directory. Can you go to vistadata in the
terminal, run svn update, and then re-run the matlab commands?

On Thu, Jan 21, 2016 at 6:22 PM, Rosemary Le <notifications@github.com>
wrote:

> The good thing is that test_CleanUpSVN seems to run without a problem:
>
> >> test_CleanUpSVN
>
> ans =
>
>      0
>
> but test_prf does return an error, which I will include in a text file
> here.
> test_prf.txt
> <https://github.com/vistalab/vistasoft/files/100056/test_prf.txt>
>
> (And indeed the mrvTest function is in the vistatest github repository,
> thanks for the clarification.)
>
> Rosemary
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vistalab/vistasoft/issues/157#issuecomment-173747927>.
>



-- 
Jonathan Winawer
Assistant Professor of Psychology and Neural Science

New York University
6 Washington Place
New York, NY, 10003
(212) 998-7922 (phone)
(212) 995-4018 (fax)
jonathan.winawer@nyu.edu
http://psych.nyu.edu/winawer/

**Comment by rosemary-le** [comment]
That did it! test_prf runs smoothly now. 

I also reran mrvTest, which ran smoothly as well. 
[mrvTestLog_2016_01_21_21-18-09.txt](https://github.com/vistalab/vistasoft/files/100368/mrvTestLog_2016_01_21_21-18-09.txt)

**Comment by JWinawer** [comment]
OK, I will merge the branches.

On Fri, Jan 22, 2016 at 1:02 AM, Rosemary Le <notifications@github.com>
wrote:

> That did it! test_prf runs smoothly now.
>
> I also reran mrvTest, which ran smoothly as well.
> mrvTestLog_2016_01_21_21-18-09.txt
> <https://github.com/vistalab/vistasoft/files/100368/mrvTestLog_2016_01_21_21-18-09.txt>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vistalab/vistasoft/issues/157#issuecomment-173820912>.
>



-- 
Jonathan Winawer
Assistant Professor of Psychology and Neural Science

New York University
6 Washington Place
New York, NY, 10003
(212) 998-7922 (phone)
(212) 995-4018 (fax)
jonathan.winawer@nyu.edu
http://psych.nyu.edu/winawer/
