### ISSUE TITLE
Remote data toolbox to replace vistadata.

### ISSUE THREAD

**Issue by wandell** [vistalab/vistasoft#158]
I created a branch (rdt) that illustrates how we can use the new remote data toolbox to read files.  The goal is to replace the vistadata svn repository with this mechanism.

On that branch, there is a new directory in vistasoft/rdt.  It contains a script showing how to read data.  Please have a look when you get a chance.

To run this script, you will need to have the remote data toolbox on your path.  It can be cloned from

   https://github.com/isetbio/RemoteDataToolbox.git

I am hoping to write more web-page tutorials to explain this and other things.  But the script is quite simple (I think).

After the toolbox seems stable, we might choose to put the whole thing in vistasoft.  Timing on that is small number of weeks.

**Comment by rosemary-le** [comment]
```
No public field PartialMatching exists for class inputParser.
```

is the weird error I'm getting when I run the first line of the tutorial. It's strange because KeepUnmatched and CaseSensitive _are_ found as properties of inputParse, and the Matlab help page does list PartialMatching as a valid field. 

This is the complete error message:
```
No public field PartialMatching exists for class inputParser.

Error in rdtInputParser (line 17)
parser.PartialMatching = false;

Error in rdtSearchParentFolders (line 21)
parser = rdtInputParser();

Error in rdtConfiguration>configFromJson (line 110)
projectConfig = rdtSearchParentFolders(jsonFileName, pwd());

Error in rdtConfiguration (line 52)
        [configArgs{1}, flavor] = configFromJson(arg);

Error in RdtClient (line 24)
            obj.configuration = rdtConfiguration(configuration);

Error in t_rdtExample (line 26)
rd = RdtClient('vistasoft');
```

**Comment by arokem** [comment]
Hey @rosemary-le - you might want to post that over on the RDT repo (https://github.com/isetbio/RemoteDataToolbox), to make sure the people working on it see it.

**Comment by rosemary-le** [comment]
Oops my bad! Thanks Ariel. :)

**Comment by arokem** [comment]
No problem. I'll leave this one open, but I will scrub away our conversation :-)

**Comment by wandell** [comment]
There has been progress (see #163). It is probably time to close this issue and start going through the test scripts to convert them for the RdtClient.
