### ISSUE TITLE
Some environment dependency in mrAnatExtractBrain.m

### ISSUE THREAD

**Issue by htakemur** [vistalab/vistasoft#169]
Hi vistasoft users, 

We are routinely starting to use the vistasoft in the cluster computer in the institute by multiple users. Here, we had issue specific to our environment. 

The problem is mrAnatExtractBrain.m

In line 76, this function defines the temporal directory and file name as follows,

out = fullfile(tempdir,'bet_tmp');

In the case of cluster, this made us some issues. 
In our case, we are sharing /tmp directory in our Ubuntu system. Then other users could not overwrite the temporary file in this folder because they don't have a permission. 

My temporary solution is to ask each user to use a different temporary file name, such as 

out = fullfile(tempdir,'bet_usrname');

but, well, this is not a smart solution.

Presumably, we should include the line to delete temporary files when we finished the preprocessing within mrAnatExtractBrain.m, and then remaining temporary file does not affect the preprocessing in other users.

**Comment by lmperry** [comment]
Thanks Hiromasa. I'm working on a solution to this issue now.
