### ISSUE TITLE
mrAnatConvertVAnatToT1Nifti bug report

### ISSUE THREAD

**Issue by edden-gerber** [vistalab/vistasoft#197]
According to its description and title the mrAnatConvertVAnatToT1Nifti.m function converts VAnat files to the nifti format. However it calls the readVolAnatHeader.m function, which happens to accept only nifti files (gives error: "Please convert your volume anatomy to nifti"). 

The same issue arises with using readVolAnat.m and mrLoad.m directly as specified in the Wiki (https://web.stanford.edu/group/vista/cgi-bin/wiki/index.php/Anatomical_Methods#Converting_vAnatomy.dat_to_a_t1_NIFTI)

**Comment by JWinawer** [comment]
This is now fixed. The function mrAnatConvertVAnatToT1Nifti now works. Moreover, there is now a new validation function to ensure that this conversion works. The test function is called 

```test_mrvConvertVAnat.m```

and can be run on its own or will be run automatically as part of mrvTest()
