### ISSUE TITLE
Is it possible to get reprojection of visual cortical activity in visual field based on retionotopic mapping data?

### ISSUE THREAD

**Issue by ahmadi123** [vistalab/vistasoft#202]
Dear mrVista experts, 
We have scanned a number of pateints who had visual aura during migraine attack and in a separate session we did retinotopy on them. We can see signal dropout while aura in different visual areas. It will be really great to kwon exactly whcih locations in visual field correspond to location of signal loss in cortex. I think there were some plotting options like co vs position/phase vs position when one could create flat view but are there similar ways to have it from mesh surface?
Any suggestion is greatly appreciated. 
Best regards, 
Ahmadi

**Comment by JWinawer** [comment]
The function _plotCorVsPhase.m_ works for volume data. If you define an ROI on the mesh, and then export the ROI to the volume (e.g., _meshROI2Volume([], 3)_), you can plot the co v phase, if that is what you want to do.

**Comment by JWinawer** [comment]
This looks to be resolved. Reopen the issue if not.
