### ISSUE TITLE
niftiView error

### ISSUE THREAD

**Issue by rosemary-le** [vistalab/vistasoft#211]
```
Error using image
Invalid datatype for Image CData. Numeric or logical matrix required for image CData.

Error in imagesc (line 18)
    hh = image(varargin{1},'CDataMapping','scaled');

Error in niftiMontage (line 70)
imagesc(m);

Error in niftiView (line 57)
    [montage, hdl] = niftiMontage(v,varargin{:});
```

What is confusing is that varargin{1} is a 2030x1914 matrix of class double, which is indeed a numeric matrix. 

Would anyone know of something that would make this file incompatible with Matlab? There does not seem to be a problem viewing this file in ITKSNAP, for example.

Thank you --

**Comment by JWinawer** [comment]
I am guessing this issue was somehow resolved. Please re-open if not.
