### ISSUE TITLE
problem with mrMeshServer in ubuntu 16.10

### ISSUE THREAD

**Issue by ahmadi123** [vistalab/vistasoft#215]
Dear mrVista experts, 
I have recently installed Ubuntu 16.10 (64 bit) and now try to get mesh server running.  I tried to execute mrMeshSrv_Ubuntu1204.glxa64. After installation of missing libraries, I was able to build, smooth, and save meshes. It was also possible to project retinotopic maps on mesh surface. However with a simple clicking on the mesh, mesh server disappears leaving an error in bash :   Segmentation fault (core dumped) but there is no error message in matlab command window and actually when I want to close gray window it asks to close mesh windows as well!
I tried to run mesh server with gdb and backtrack it but it is not very informative. (Please find the attached file).
Does it happen because I am using a different version of Ubuntu? If it is the case, I also tried recompiling  mrMeshSrv via the link below:
https://web.stanford.edu/group/vista/cgi-bin/wiki/index.php/MrMesh
but wasn't successful. It is worth mentioning that I have installed all the required libraries and packages. Any suggestion is greatly appreciated.
Best regards, 
Ahmadi 
![mrmeshserver](https://cloud.githubusercontent.com/assets/10156565/21187029/ced01288-c216-11e6-8523-6e6e451840ac.png)

**Comment by allanhummer** [comment]
I also struggle with compiling mrMeshSrv on Ubuntu 16.04. Any help would be greatly appreciated.

**Comment by JWinawer** [comment]
@ahmadi123, @allanhummer, are you still getting crashes from the mesh server on Ubuntu?

Has anyone else been able to use the mesh server successfully on ubuntu?

**Comment by ahmadi123** [comment]
Hi, 
I couldn't solve the errors in Ubuntu 16.10 and had to down grade to Ubuntu 12.4 to use the compiled code. I had still the same problem. Then I realized that the default graphics in Ubuntu is "nouveau" which lacks proprietary 3D accelerated features that are required for mrMesh. After changing the graphical drivers, mesh server did not crash. However, it was giving wrong colours while projecting the retinotopic maps on to surface but following your suggestion from #238 was very helpful and finally it is working now!
Thanks a lot and best, 
Khazar Ahmadi
