### ISSUE TITLE
MrDiffusion:initial error in dtiFiberUI function

### ISSUE THREAD

**Issue by duartemhgoncalves** [vistalab/vistasoft#217]
Hello!
I write Thaís post about the installation of MrDiffusion software. When i open dtiFiberUI in MatLab, open the window mrdMain1 and i trie open dt6.mat file (get this from mrdiffusion sample data) but appear the follow error in matlab command:
```

>> fig = dtiFiberUI('dt6.mat')
An error occurred in mrDiffusion:
Undefined function or variable 'dtiRoiEditGetPen'.
Thrown in:
C:\Users\Duarte\Documents\MATLAB\Tese\mrDiffusion\GUI\dtiFiberUI.m line 356
??? Undefined function or method 'ieNotDefined' for input arguments of type
'char'.

Error in ==> dtiMrMeshInit at 9
if ieNotDefined('id'), id = 174; end

Error in ==> dtiFiberUI at 118
    handles.mrMesh = dtiMrMeshInit(174);
```

The error is about the initialize parameters and i don't know how to solve it. 
Someone can give me help to solve this error?

I appreciate your help!

**Comment by wandell** [comment]
Your error message confuses me a bit.  One part says ieNotDefined() is undefined.  That function is here:
   . ../vistasoft/external/iset/ieNotDefined.m

Another part says undefined dtiRoiEditGetPen.  That function is here
   .../vistasoft/mrDiffusion/roi/dtiRoiEditGetPen.m

So, perhaps your path is not set properly.

**Comment by duartemhgoncalves** [comment]
I know that can be confuse my question. I think that are related with the path of files. 
The path to matlab should have the folder vistasoft, but should have all the files that i need (example:all that exist within mrdiffusion) within this folder?
Within the vistasoft folder i can't have any subfolder, rigth?
(I don't find information about the especific Path and files that i must have to work with MatLab)

**Comment by arokem** [comment]
Yes. You need all sub-folders on your path as well.

To get all the functions on your path, I believe you can run:

    addpath(genpath('/full/path/to/vistasoft'))

**Comment by duartemhgoncalves** [comment]
Arokem,
Thank you for your help. It's work well!
