### ISSUE TITLE
Running dtiInit and encountering error

### ISSUE THREAD

**Issue by jwjjwong** [vistalab/vistasoft#241]
I encounter an error when running dtiInit using the following command:
[dt6FileName, outBaseDir] = dtiInit('raw/dwi.nii.gz','t1.nii.gz',dwParams);

The following error messages come up:
[dtiRawRohdeEstimateEddyMotion] These transforms map voxels in the reference image (usually the mean b=0) to each raw image.
Error using num2str (line 45)
Input to num2str must be numeric.

Error in dtiCheckMotion (line 64)
    num2str(fh),figurename);

Error in dtiInit (line 163)
   dtiCheckMotion(dwDir.ecFile,'off');

I checked the actual line and it reflects the following:
printCommand = ...
    sprintf('print(%s, ''-painters'',''-dpng'', ''-noui'', ''%s'')', ...
    num2str(fh),figurename);
I just commented out lines 62-67 of dtiCheckMotion script, and the command works.  Are there any problems if I do that?

**Comment by Drigomaniac** [comment]
I ran into this similar issue. I think the problem is compatibility with later MATLAB versions. I believe a good fix will be to change line 41 (in dtiCheckMotion.m):

There is a class check `if isstruct(fh)` to see whether variable `fh` is of struct form or not but now 
`fh` has its own class definition `matlab.ui.Figure`. Hence, it will never assign a number. 

So if we change line 41 to `if ~isnum(fh)` instead, then it will always access when fh is not a number. 

I am starting to understand github and I would like to contribute fixing this (and other) problems. What is the best strategy to do so? 
thanks,
Rodrigo

**Comment by arokem** [comment]
This seems like a pretty good how-to on the topic: http://blog.davidecoppola.com/2016/11/howto-contribute-to-open-source-project-on-github/

**Comment by Drigomaniac** [comment]
@jwjjwong or alternatively, you may use the most up to date Matlab version tree branch of vistasoft ?

**Comment by jwjjwong** [comment]
@Drigomaniac I am using Matlab2015b, is that not updated enough?  Thanks for the tips, I will try editing this if I run into the issue again.

**Comment by JWinawer** [comment]
It looks like this issue is closed. Pls reopen if there are continued problems.

**Comment by soichih** [comment]
I am ranning into a similar problem with Matlab r2017a with the latest master branch of Vistasoft.

```
{Error using num2str (line 45)
Input to num2str must be numeric.

Error in dtiCheckMotion (line 64)
    num2str(fh),figurename);

Error in dtiInit (line 163)
   dtiCheckMotion(dwDir.ecFile,'off');

Error in main (line 43)
dtiInit(config.dwi, config.t1, dwParams)
} 
```

Is r2017a supported by Vistasoft?

Following is how I am running dtiInit

```
% load my own config.json
config = loadjson('config.json');

% to find resolution
dwi = niftiRead(config.dwi);
res = dwi.pixdim(1:3);
clear dwi

dwParams = dtiInitParams;
dwParams.clobber           =  1;
dwParams.eddyCorrect       = -1;
dwParams.phaseEncodeDir    = 2;
dwParams.rotateBvecsWithRx = 0;
dwParams.rotateBvecsWithCanXform = 0;
dwParams.bvecsFile  = config.bvecs;
dwParams.bvalsFile  = config.bvals;
dwParams.dt6BaseName = 'dti';
dwParams.outDir     = pwd;
dwParams.dwOutMm    = res;
dwParams.outDir = 'output';

%apply config params
if isfield(config, 'eddyCorrect')
    dwParams.eddyCorrect = str2double(config.eddyCorrect);
    dwParams.rotateBvecsWithRx = config.rotateBvecsWithRx;
    dwParams.rotateBvecsWithCanXform = config.rotateBvecsWithCanXform;
end

dtiInit(config.dwi, config.t1, dwParams)

```

And the config.json contains following

```
{
    "t1": "/N/u/hayashis/Karst/testdata/app-dtiinit/t1.nii.gz",
    "dwi": "/N/u/hayashis/Karst/testdata/app-dtiinit/dwi.nii.gz",
    "bvecs": "/N/u/hayashis/Karst/testdata/app-dtiinit/dwi.bvecs",
    "bvals": "/N/u/hayashis/Karst/testdata/app-dtiinit/dwi.bvals",
    "eddyCorrect": "1",
    "rotateBvecsWithRx": false,
    "rotateBvecsWithCanXform": false
}
```

**Comment by soichih** [comment]
Following patch seems to fix this problem

```
[brlife@h3 vistasoft]$ git diff
diff --git a/mrDiffusion/preprocess/dtiCheckMotion.m b/mrDiffusion/preprocess/dtiCheckMotion.m
index 06a3943..0027e5b 100644
--- a/mrDiffusion/preprocess/dtiCheckMotion.m
+++ b/mrDiffusion/preprocess/dtiCheckMotion.m
@@ -38,7 +38,7 @@ t = vertcat(ec.xform(:).ecParams);
 % We make a plot of the motion correction during eddy current correction
 % but we do not show the figure. We only save it to disk.
 fh = mrvNewGraphWin([],[],visibility);
-if isstruct(fh)
+if isgraphics(fh)
     fh = fh.Number; 
 end

```

**Comment by francopestilli** [comment]
@jyeatman this was introduced in your last push to save the motion estimates figure. IF it is not a conflict I would like to move on and change it back to if isgraphics(fh)

Please let me know ASAP! 

Thank you.

**Comment by francopestilli** [comment]
@jyeatman @JWinawer @htakemur 
https://github.com/vistalab/vistasoft/commit/c56ceb8f986fdf3e85974c68ca87e0ef2d140ed3

**Comment by jyeatman** [comment]
This will make vistasoft incompatible with matlab prior to 2014b. Is there
any way to use a function other than isgraphic?

Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://brainandeducation.com

**Comment by francopestilli** [comment]
But unfortunately, the current version of this function is incompatible with the current version of MatLab.

Can ypu please test one of the following on your 2014b?
ishandle(h1)
isvalid(h1)

Does any of these work for you?

**Comment by jyeatman** [comment]
ishandle is a function in 2014 so that should work

Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://brainandeducation.com
