### ISSUE TITLE
Error Setting Retinotopy Stimulus Parameters during pRF Tutorial

### ISSUE THREAD

**Issue by ejduwell** [vistalab/vistasoft#263]
Hello Experts,

I am brand new to mrVista/vistasoft and have been trying to walk myself through the pRF Modeling tutorial: http://web.stanford.edu/group/vista/cgi-bin/wiki/index.php/PRF_Tutorial. Everything appeared to work well until I got to part (3) DEFINE THE STIMULUS PARAMETERS. At this point, in the volume window, I go to Analysis-->Retinotopic Model-->Set parameters. The tutorial says that the parameters for the sample data set should already be set appropriately, and to hit Done. At this point, I get the the following series of error messages:

Error using optimset (line 148)
No default options available for the function 'fmincon'.

Error in rmDefineParameters (line 572)
params.analysis.fmins.options = optimset('fmincon');

Error in rmLoadParameters (line 17)
params = rmDefineParameters(vw);

Error in rmEditStimParams>paramsToVista (line 776)
handles.vw = rmLoadParameters(handles.vw);

Error in rmEditStimParams>btnDone_Callback (line 739)
paramsToVista(hObject,handles);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in rmEditStimParams (line 45)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)rmEditStimParams('btnDone_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback

Does anyone know what might be causing this error with fmincon? If so, I would really appreciate some advice.

Many Thanks,
Ethan

**Comment by JWinawer** [comment]
Based on the other issue (https://github.com/vistalab/vistasoft/issues/264), this issue appears to have been solved by adding the optimization toolbox. Please re-open if it remains a problem.
