### ISSUE TITLE
dt6.mat isn't centered in viewer

### ISSUE THREAD

**Issue by aeppes** [vistalab/vistasoft#283]
![capture](https://user-images.githubusercontent.com/11219929/37224879-c4472510-23a2-11e8-8742-5c00a9c1ea46.PNG)
After running dtiInit.m, when I load dt6.mat into dtiFiberUI the image isn't centered. The image is collected on SIEMENS machine and it seems the error is occurs from the t1. Any ideas are appreciated, thank you!

**Comment by francopestilli** [comment]
I believe you want to run an AC-PC alignment first. https://github.com/vistalab/vistasoft/wiki/ACPC-alignment

**Comment by aeppes** [comment]
This worked great, thank you!
