### ISSUE TITLE
Interpolation methods

### ISSUE THREAD

**Issue by soanduong** [vistalab/vistasoft#305]
Hi experts,

Do you know the core difference between the `myCinterp3` and `spm_bsplinc` interpolation function?

As far as I understand, I think they are just different in the way of approximating the point for interpolation, so they should provide interpolated images quite the same.

However, when I put the same input data (of course, they are formatted to fit each function), I got totally different interpolated results. 

Could anyone point me out where am I wrong or misunderstood? Any offer you have would be highly appreciated.

Best,
Soan

**Comment by JWinawer** [comment]
To my knowledge, myCinterp does linear interpolation. spm_bsplinc does
spline interpolation, which is non-linear (piece-wise polynomial).
Depending on the data being interpolated, the results could be very similar
or not. I would guess that they would be similar under most typical
MRI-related data sets (e.g., time series or anatomical images). So if they
are dramatically different there might be something wrong with the
computation.

On Thu, Dec 6, 2018 at 7:20 AM Soan Thi Minh Duong <notifications@github.com>
wrote:

> Hi experts,
>
> Do you know the core difference between the myCinterp3 and spm_bsplinc
> interpolation function?
>
> As far as I understand, I think they are just different in the way of
> approximating the point for interpolation, so they should provide
> interpolated images quite the same.
>
> However, when I put the same input data (of course, they are formatted to
> fit each function), I got totally different interpolated results.
>
> Could anyone point me out where am I wrong or misunderstood? Any offer you
> have would be highly appreciated.
>
> Best,
> Soan
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_vistalab_vistasoft_issues_305&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=W4u2U_DhoNoJOD0UdsYQiqH56Bg3zFfOtNa0RCuuEIs&m=suUP4hTvEpSGy_PfPPcFEgGdLdbQrNABrSIH64loJDo&s=Sm09UWi4eAZF0FHjyCrMiiyrI99FCUO-HFASzBFAcPg&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ACBX3jXKg2ZMJHLcF5cigAM5GPUOLQebks5u2Qt1gaJpZM4ZGZjC&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=W4u2U_DhoNoJOD0UdsYQiqH56Bg3zFfOtNa0RCuuEIs&m=suUP4hTvEpSGy_PfPPcFEgGdLdbQrNABrSIH64loJDo&s=MeL7Hk5aRk2-yxJPAJjvcKnvj4CAyvjUKCClDyfkIfo&e=>
> .
>


-- 
Jonathan Winawer
Assistant Professor of Psychology and Neural Science

New York University
6 Washington Place
New York, NY, 10003
(212) 998-7922 (phone)
(212) 995-4018 (fax)
jonathan.winawer@nyu.edu
http://psych.nyu.edu/winawer/

**Comment by JWinawer** [comment]
Closing. Please re-open if there are more questions.
