### ISSUE TITLE
Undefined function or variable 'fileNameExtended'.

### ISSUE THREAD

**Issue by soichih** [vistalab/vistasoft#307]
If an input flie is missing, it tries to report it but fails to do so as fileNameExtended is not defined.

https://github.com/vistalab/vistasoft/blob/2e60ffd6ecfa91df214166dfd5f5d554ed45ff01/fileFilters/nifti/niftiRead.m#L52

**Comment by wandell** [comment]
Good catch.  I pushed a fix.
