### ISSUE TITLE
MATLAB version dependency, dtiCheckMotion.m

### ISSUE THREAD

**Issue by htakemur** [vistalab/vistasoft#310]
My colleague found that sometimes this code has dependency on MATLAB version. 

It is most likely that this occurs because of figure handle depends on MATLAB version here (lines 62-64). 

printCommand = ...
    sprintf('print(%s, ''-painters'',''-dpng'', ''-noui'', ''%s'')', ...
    num2str(fh),figurename);

I'm trying to look into code and hopefully fix this dependency.

**Comment by francopestilli** [comment]
good cath. It should return the figure handle from the fh structure instead.

**Comment by htakemur** [comment]
Thanks. I performed a pull request, and hopefully it will fix this issue. I have tested a newer version in newer matlab (2017a and 2018a), and at least it didn't make error at this part.

**Comment by htakemur** [comment]
This issue should be solved.
