### ISSUE TITLE
Issue with nifti2ROI

### ISSUE THREAD

**Issue by hhal** [vistalab/vistasoft#313]
Hi all,

I'm having an issue with the nifti2ROI script.

I've defined a lesion mask in a stroke patient, and want to load this lesion as a ROI in mrVista. Lesion is in 'RAS'. The mask aligns with the t1 thas has been used in the mrVista analysis. 

I'm using the nifti2ROI script to import this ROI and that has nifti2mrVistaAnat implemented which should re-orient the nifti to mrVista Anatomy convention. 

The script runs errorless, however, the lesion ROI still seems not to be oriented correctly. In fact, it falls completely outside the brain. 

When, for example, I'm using the same script to install the probability atlas of Wang (as described here) I don't run into any problems. 

Any clue what when wrong?

**Comment by JWinawer** [comment]
Does the lesion ROI file have the identical header to the T1 anatomy?

On Tue, Apr 16, 2019 at 6:18 AM hhal <notifications@github.com> wrote:

> Hi all,
>
> I'm having an issue with the nifti2ROI script.
>
> I've defined a lesion mask in a stroke patient, and want to load this
> lesion as a ROI in mrVista. Lesion is in 'RAS'. The mask aligns with the t1
> thas has been used in the mrVista analysis.
>
> I'm using the nifti2ROI script to import this ROI and that has
> nifti2mrVistaAnat implemented which should re-orient the nifti to mrVista
> Anatomy convention.
>
> The script runs errorless, however, the lesion ROI still seems not to be
> oriented correctly. In fact, it falls completely outside the brain.
>
> When, for example, I'm using the same script to install the probability
> atlas of Wang (as described here) I don't run into any problems.
>
> Any clue what when wrong?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_vistalab_vistasoft_issues_313&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=W4u2U_DhoNoJOD0UdsYQiqH56Bg3zFfOtNa0RCuuEIs&m=eu3WOsk_U2beibW7eOm-PTUtI85oH2cGihYbJUwq5hI&s=KoBB0mCBxtd4qtl2ttO7TcpiyXxFk0k5v7sKpRYo4E4&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ACBX3pc8eZJVh8ZD9JieGhmAViECNmW7ks5vhaOMgaJpZM4cx4QI&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=W4u2U_DhoNoJOD0UdsYQiqH56Bg3zFfOtNa0RCuuEIs&m=eu3WOsk_U2beibW7eOm-PTUtI85oH2cGihYbJUwq5hI&s=pBGM4sFjWt9lkJh3_Ui2Dc9EHOsVU5SyOfsT6Wng-Y8&e=>
> .
>


-- 
Jonathan Winawer
Assistant Professor of Psychology and Neural Science

New York University
6 Washington Place
New York, NY, 10003
(212) 998-7922 (phone)
(212) 995-4018 (fax)
jonathan.winawer@nyu.edu
http://psych.nyu.edu/winawer/

**Comment by hhal** [comment]
Hi Jonathan,

Thanks for the swift reply. 

Just wanted to update on this issue. In the meantime I found the cause of the misalignment. And yes, indeed by checking the header information I found out that the qoffset_x/y/z values differed between the two niftis!

Best,

**Comment by JWinawer** [comment]
This issue looks resolved. Please re-open if not.
