### ISSUE TITLE
Macbook operating systems (Specs) for a new lab macbook: mrMesh

### ISSUE THREAD

**Issue by fails1to1compile09** [vistalab/vistasoft#327]
In our lab, I need a lab laptop that can run mrVista. While I have succeeded multiple times in getting most of mrVista to run on both Windows and Ubuntu, I keep having trouble with getting mrMesh to run on Linux. This system has crashed multiple times, despite checking advice online and from personal contacts who use mrMesh as well.

On my personal Macbooks (El Capitan, Mojave), I got mrVista and mrMesh to run without any problems, but I have read about issues with, e.g., High Sierra.
I can most likely not get exactly the same specs for a new lab Macbook. 

My question to fellow Macbook users: what version of Mac OS are you using currently? Are there any known unpublished issues with the newer Mac OS systems (Mojave, Catalina?)? Do you have input on what kind of Macbook specs to look for (or watch out for)?

**Comment by JWinawer** [comment]
I have been using vistasoft and the associated mesh tools with many
versions of Mac OS without problem. Currently, I use Catalina and it works
fine (as did the previous Mac OS).

Jon

On Wed, Jan 15, 2020 at 8:30 AM fails1to1compile09 <notifications@github.com>
wrote:

> In our lab, I need a lab laptop that can run mrVista. While I have
> succeeded multiple times in getting most of mrVista to run on both Windows
> and Ubuntu, I keep having trouble with getting mrMesh to run on Linux. This
> system has crashed multiple times, despite checking advice online and from
> personal contacts who use mrMesh as well.
>
> On my personal Macbooks (El Capitan, Mojave), I got mrVista and mrMesh to
> run without any problems, but I have read about issues with, e.g., High
> Sierra.
> I can most likely not get exactly the same specs for a new lab Macbook.
>
> My question to fellow Macbook users: what version of Mac OS are you using
> currently? Are there any known unpublished issues with the newer Mac OS
> systems (Mojave, Catalina?)? Do you have input on what kind of Macbook
> specs to look for (or watch out for)?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_vistalab_vistasoft_issues_327-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAAQFPXT3USCC3P5F25QD5ZDQ542VVA5CNFSM4KHGKPLKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IGM2P2Q&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=W4u2U_DhoNoJOD0UdsYQiqH56Bg3zFfOtNa0RCuuEIs&m=f5CDgsjgIowBCp2Z4ug92ZC6rS92DlZgaMjI10638TI&s=oKhHq1WbDjG14qIjEyEL0sHiYzfrqcXWsQyO0d0qCmE&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAQFPXQD4FYSOHZ4565OO4TQ542VVANCNFSM4KHGKPLA&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=W4u2U_DhoNoJOD0UdsYQiqH56Bg3zFfOtNa0RCuuEIs&m=f5CDgsjgIowBCp2Z4ug92ZC6rS92DlZgaMjI10638TI&s=-alDF3OfIr5K7aKPlZCoieFrTGMB2YUqDou490gCO10&e=>
> .
>


-- 
Jonathan Winawer
Associate Professor of Psychology and Neural Science

New York University
6 Washington Place
New York, NY, 10003
(212) 998-7922 (phone)
(212) 995-4018 (fax)
jonathan.winawer@nyu.edu
http://psych.nyu.edu/winawer/

**Comment by fails1to1compile09** [comment]
Dear Prof. Winawer,
Thank you so much. That is very good to know.
Yours,
F

**Comment by JWinawer** [comment]
Sorry, I seem to have made an error. I have been using the mesh tools
though Mohave. I thought I was also using it on Catalina but I was not (I
was using a Catalina laptop but running on remote desktop with a machine
running Mohave). I believe it will not work on Catalina because that
requires 64 bit apps. So we'll need to do something about that.

On Sun, Jan 19, 2020 at 1:24 AM fails1to1compile09 <notifications@github.com>
wrote:

> Dear Prof. Winawer,
> Thank you so much. That is very good to know.
> Yours,
> F
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_vistalab_vistasoft_issues_327-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAAQFPXRPKJ2UQZ3YQUCSUNTQ6QL4LA5CNFSM4KHGKPLKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJKNEOA-23issuecomment-2D575984184&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=W4u2U_DhoNoJOD0UdsYQiqH56Bg3zFfOtNa0RCuuEIs&m=E4m_g71KaeBUZE9EYOD8GyhCsORmL6Vrm8vxemVj5fo&s=wpIfoyQan6dMypnuX1fuSwD0S_nJ8SfCs6Mkw0kLM9g&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAQFPXTV3WIBNJ4ZN2DDRKTQ6QL4LANCNFSM4KHGKPLA&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=W4u2U_DhoNoJOD0UdsYQiqH56Bg3zFfOtNa0RCuuEIs&m=E4m_g71KaeBUZE9EYOD8GyhCsORmL6Vrm8vxemVj5fo&s=f4-vapPRg047_KJ7UWVvCX8xWg6UZAbwwkkdBrQNAYc&e=>
> .
>


-- 
Jonathan Winawer
Associate Professor of Psychology and Neural Science

New York University
6 Washington Place
New York, NY, 10003
(212) 998-7922 (phone)
(212) 995-4018 (fax)
jonathan.winawer@nyu.edu
http://psych.nyu.edu/winawer/

**Comment by JWinawer** [comment]
Dear F,

If this issue is resolved, could you please close it?

Jon

**Comment by fails1to1compile09** [comment]
Dear Professor Winawer,

Although the issue of probably not being able to run mrMesh on Catalina is not resolved, I suppose the issue was not knowing whether it was possible to run mrMesh on Catalina or not. Thus, I guess the issue is hereby closed.

Yours,

F

**Comment by fails1to1compile09** [comment]
Sorry for not closing the issue. I didn't realise this one should be closed, because it was about not knowing which Macbook systems mrMesh runs on. Not about probably being unable to run it on Macbook Catalina. Thank you so much for the information and for opening a more specific issue related to mrMesh/Vistasoft on Macbook Catalina.
