### ISSUE TITLE
Load the retinotopy model file from command line

### ISSUE THREAD

**Issue by marco-create** [vistalab/vistasoft#339]
Hello experts,

is there a way to load the ret model (created after run pRF analysis) using the command line, instead of using the GUI?

With the GUI, I used to click: **File | Retinotopy Model | Select and Load Model**

Thank you,
Marco

**Comment by JWinawer** [comment]
Yes.

vw = initHiddenGray();
vw = rmSelect(vw, loadModel, rmFile)

On Thu, Jul 23, 2020 at 10:03 AM marco-create <notifications@github.com>
wrote:

> Hello experts,
>
> is there a way to load the ret model (created after run pRF analysis)
> using the command line, instead of using the GUI?
>
> With the GUI, I used to click: *File | Retinotopy Model | Select and Load
> Model*
>
> Thank you,
> Marco
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_vistalab_vistasoft_issues_339&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=W4u2U_DhoNoJOD0UdsYQiqH56Bg3zFfOtNa0RCuuEIs&m=aTAWEj4Og5rKU7m_nJQISYPs5ScJmYwEqYec7AnJ_vc&s=yZyIkZNpSrJg-1mtilrGpdkPPLJAiujMkEPnZLX4vso&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAQFPXQH5OEZ2ZVGVJGJEITR5A7HXANCNFSM4PFYEHBA&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=W4u2U_DhoNoJOD0UdsYQiqH56Bg3zFfOtNa0RCuuEIs&m=aTAWEj4Og5rKU7m_nJQISYPs5ScJmYwEqYec7AnJ_vc&s=MnkiHdhDLYCuXE7ceBNKBEtZkUMeLWpJBqYhLS2s5pQ&e=>
> .
>


-- 
Jonathan Winawer
Associate Professor of Psychology and Neural Science

New York University
6 Washington Place
New York, NY, 10003
(212) 998-7922 (phone)
(212) 995-4018 (fax)
jonathan.winawer@nyu.edu
http://psych.nyu.edu/winawer/
