### ISSUE TITLE
Writing tck file from vistasoft....

### ISSUE THREAD

**Issue by htakemur** [vistalab/vistasoft#341]
Hello,

When I tried to see .tck file exported from vistasoft in MRView, I got a following error: 

![Mrview_Errormessage](https://user-images.githubusercontent.com/2679022/90847075-a3c59c80-e3a4-11ea-87fb-14f5e5b396d9.png)

I guess that perhaps some information on .tck export may not have some header information required in MRView. If any of you had a similar experience, I would like to discuss how to move forward.

**Comment by soichih** [comment]
@Hiromasa Takemura <htakemura0207@gmail.com>

I can't think of why this is happening, can you run "head track.tck" to
show what's at the top of your .tck? You should see something like

```
mrtrix tracks
act: 5tt.mif
backtrack: variable
crop_at_gmwmi: 1
downsample_factor: 3
fod_power: 0.25
init_threshold: 0.0500000007
lmax: variable
max_angle: variable
max_num_seeds: 15000000
...

```

By the way, I am attending some personal business. I might not be able to
respond until later next week.

**Comment by htakemur** [comment]
I will have a look at header informations, and try to compare those of tck files which work and do not work with mrView. I appreciate your response; I will try to handle it by myself at this moment.

**Comment by htakemur** [comment]
I think that I figured out the issue --- please see my pull request. I will close this issue.
