### ISSUE TITLE
Problems with framePeriod and antomical inplane

### ISSUE THREAD

**Issue by sunflowercyh** [vistalab/vistasoft#35]
It seems that Vistasoft cannot recognize framePeriod of our data(Siemens dicom, one dicom contains all slices within a TR) correctly. For example, our TR was 1.5s, while the framePeriod showed in dataTYPES was 3.0125. I thought this error maybe due to wrong slice duration, and the slice duration dimed  in nifti was 0.045.  Slices of our functional data is 25, TR is 1.5s so the slice duration was 0.06s(1.5s/25), right?  So I changed the sliceduration, but framePeriod was still 3.0125. At last I changed the value of framePeriod to 1.5 in the dataTYPES directly. I wonder  what determines the value of framePeriod in vistasoft code and is modifying it in dataTYPES a feasible solution?

Another issue is about the anatomical inplane.1) inplane's path. In mrsession.mat created by new code, inplanePath is something like '/media/36E67512E674D399/radilil/functionals/mean.nii', this can be a bit trouble because a disk in Linux named 36E67512E674D399 may be called  F in Windows, so when open in different operating systems or computers, I need to change the path everytime. Can this be solved by changing code and don't store path with the disk name, for example,  'new/functionals/mean.nii' maybe enough in most of the situations as long as files needed are in the same disk. 2) In mutual information alignment anat.mat is still needed, so if users want to run mrAlignMI they need to make one with command line. I think perhaps modify the code to find anat.mat in mrsession.mat will be more convenient.

**Comment by JWinawer** [comment]
I am closing this issue. Please re-open if there is a current question.
