### ISSUE TITLE
convert Camino .Bfloat file into Quench .pdb format

### ISSUE THREAD

**Issue by lulu1990** [vistalab/vistasoft#37]
Hello, experts,

I want to do retinotopic white matter with my hardi data using both Quench and Camino. When I was trying to convert Camino .Bfloat file into Quench .pdb format, I met some errors. It seemed that,  mtrImportFibers.m function(fg = mtrImportFibers(tractsFile,eye(4)); ) can't read or calculate the parameters in my tractsfile. The warnings and all codes I refered are listed below. Can someone help me to solve this problem?  Thanks in advance!
![2013-04-26_203107](https://f.cloud.github.com/assets/4263194/430529/350b19d2-ae6e-11e2-8b1e-e7193da7f7eb.jpg)

??? Error using ==> horzcat
The following error occurred converting from char
to struct:
Error using ==> struct
Conversion to struct from char is not possible.

Error in ==> fiberToStr3 at 53
        disp(['Warning: Invalid param "'
        fg.params{ff} '" ... skipping']);

Error in ==> mtrExportFibers at 146
		str=fiberToStr3(fg);

All codes I've refered:

% Load seed volume
seedFile = 'camino/wm.nii.gz';
seedNI = readFileNifti(seedFile);

% Calc xform from camino space to surface data
xformMMToSeed = seedNI.qto_ijk;
xformMMToSeed(1:3,4) = 0;
xformSeedToAcPc = seedNI.qto_xyz;
xformAcPcToSurface = surfaceNI.qto_ijk;
xformMMToSurface = xformAcPcToSurface * xformSeedToAcPc * xformMMToSeed;

% Load camino path file
tractsFile = 'camino/tracts.Bfloat';
fg = mtrImportFibers(tractsFile,eye(4));

% Get fibers into AcPc
fg_acpc = dtiXformFiberCoords(fg, xformSeedToAcPc * xformMMToSeed);

% write the fibers into a pdb file
mtrExportfibers(fg_acpc,'fibers.pdb');

**Comment by JWinawer** [comment]
This issue is a year and a half old. I am closing it. Please re-open if there is a current question.
