### ISSUE TITLE
Cannot compile readFileNifti and writeFileNifti from mrvCompile

### ISSUE THREAD

**Issue by j-ales** [vistalab/vistasoft#64]
Platform: OSX 10.8.4 Matlab R2013a
 
First problem: defaultCFileList.m points to 'fileFilters/nifti/' instead of fileFilters/nifti/C-code'

After fixing that I get a second problem: znzlib.h is missing. 

Error message:
[mrvCompile]: Trying to compile /Users/babylab/MATLAB/vistasoft/fileFilters/nifti/C-code/writeFileNifti.c /Users/babylab/MATLAB/vistasoft/fileFilters/nifti/C-code/nifti1_io.c /Users/babylab/MATLAB/vistasoft/fileFilters/nifti/C-code/znzlib.c... (23-Jul-2013 11:36:36)
In file included from /Users/babylab/MATLAB/vistasoft/fileFilters/nifti/C-code/writeFileNifti.c:36:
/Users/babylab/MATLAB/vistasoft/fileFilters/nifti/C-code/nifti1_io.h:20:10: fatal error: 
      '../zlib/znzlib.h' file not found
#include "../zlib/znzlib.h"

**Comment by JWinawer** [comment]
This issue appears to be resolved. Please re-open it if a question remains.
