### ISSUE TITLE
Matlab file version of readFileNifti.m does not work to open mrBOLD_01 in vistadata

### ISSUE THREAD

**Issue by j-ales** [vistalab/vistasoft#65]
Platform OSX 10.8.4  Matlab R2013a
Trying to open the mrBOLD_01 session using readFileNifti.m, without the mex compiled version results in an error.

Error message:

Initializing Inplane view
Attaching menus
Using the matlab version of the niftiReader....
Error using xform_nii>change_hdr (line 350)

   Non-orthogonal rotation or shearing found inside the affine matrix
   in this NIfTI file. You have 3 options:
1. Using included 'reslice_nii.m' program to reslice the NIfTI
     file. I strongly recommand this, because it will not cause
     negative effect, as long as you remember not to do slice
     time correction after using 'reslice_nii.m'.
2. Using included 'load_untouch_nii.m' program to load image
     without applying any affine geometric transformation or
     voxel intensity scaling. This is only for people who want
     to do some image processing regardless of image orientation
     and to save data back with the same NIfTI header.
3. Increasing the tolerance to allow more distortion in loaded
     image, but I don't suggest this.
   
   To get help, please type:
   
   help reslice_nii.m
   help load_untouch_nii.m
   help load_nii.m

Error in xform_nii (line 154)
   [hdr,orient]=change_hdr(hdr,tolerance,preferredForm);

Error in load_nii (line 135)
   nii = xform_nii(nii, tolerance, preferredForm);

Error in readFileNifti (line 55)
   nii = load_nii(tmpFileName, volumesToLoad);

Error in niftiRead (line 34)
    ni = readFileNifti(fileName);

Error in viewSetAnatomy (line 32)
        vw = viewSet(vw,'Anatomy Nifti', niftiRead(val));

Error in viewSet (line 188)
        vw = viewSetAnatomy(vw,param,val,varargin{:});

Error in loadAnat (line 34)
        vw = viewSet(vw,'Anat Initialize',pathStr);

Error in openMontageWindow (line 157)
INPLANE{s} = loadAnat(INPLANE{s}, sessionGet(mrSESSION,'Inplane Path'));

Error in mrVista (line 83)
       [vw, s] = openMontageWindow;

**Comment by Deliagirl** [comment]
> Seems to me from the error that we should be using load_untouch_nii instead of load_nii, so as to not run into issues with the affine, but also so that it doesn't get resliced. Does seem about right to you?

You are so great!!!Thank U very much!!!
